### ISSUE TITLE
__init__() missing 1 required positional argument: 'engine' loading "/"

### ISSUE THREAD

**Issue by aedoran** [wq/wq.db#45]
After going through the installation procedure here:
https://wq.io/docs/setup

using ubuntu 14.04

TypeError at /
__init__() missing 1 required positional argument: 'engine'
Request Method:	GET
Request URL:	
Django Version:	1.8.2
Exception Type:	TypeError
Exception Value:	
__init__() missing 1 required positional argument: 'engine'
Exception Location:	/usr/local/lib/python3.4/dist-packages/wq/db/rest/template.py in get_template_source, line 9
Python Executable:	/usr/bin/python3
Python Version:	3.4.0
Python Path:	
['/home/wq/proj/da/db',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages']
Server time:	Mon, 25 May 2015 16:10:39 +0000

**Comment by sheppard** [comment]
Thanks for reporting this.  My guess would be that you have Django 1.8 installed together with wq.db 0.7.2.  The instructions at https://wq.io/docs/setup tell you to install the `wq` meta package, which automatically installs matching versions of wq.app, wq.db, and wq.io.  For example, installing wq 0.7 installs the latest 0.7.x versions of each submodule.  The latest version of wq.db is 0.8.0, but the wq metapackage is still stuck on 0.7 since wq.app 0.8.0 hasn't been released yet.

Sorry for the inconvenience - all of this will be resolved with the release of wq.app 0.8.0 sometime in the next two weeks.  For now, you can get around this by explicitly installing wq.db 0.8.0.  You will likely also want to upgrade to the latest version of the wq template (wq.start).  wq.app 0.7.4 is forward-compatible with wq.db 0.8.0 and the updated template.

The following commands should do the trick:
```bash
sudo pip3 install wq.db==0.8.0
sudo pip3 install wq.start==0.8.0
```

The other option would be to downgrade Django to 1.7, but I'd recommend just upgrading wq.db since the latest version has a number of [improvements and API changes](https://github.com/wq/wq.db/releases/tag/v0.8.0).

**Comment by aedoran** [comment]
cool that worked thank!

**Comment by sheppard** [comment]
Closing now that [wq 0.8](https://github.com/wq/wq/releases/v0.8.0) is released.
