### ISSUE TITLE
"This field may not be null." for models.CharField declared with blank=True

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.db#58]
There is an inconsistency of client- and server-side validation for CharField fields with blank=True.
The generated templates accept such an object, but the synchronization fails. The outbox synchronization process sends these fields as "", but the server responds with "400 Bad Request" with a JSON structure containing "This field may not be null." messages.

**Comment by sheppard** [comment]
Yes, this is a bug in wq.db's [`ModelSerializer`](https://github.com/wq/wq.db/blob/master/rest/serializers.py), which converts all incoming `""` to `None` before running the validation.  A temporary workaround would be to create a custom `ModelSerializer` that restores the blank value:

```python
# myapp/serializers.py
from wq.db.rest.serializers import ModelSerializer

class MyModelSerializer(ModelSerializer):
    def to_internal_value(self, data):
        result = super().to_internal_value(data)
        if result.get('fieldname', None) is None:
            result['fieldname'] = ""
        return result

# myapp/rest.py
from wq.db import rest
from .serializers import MyModelSerializer
from .models import MyModel

rest.router.register_model(
    MyModel,
    serializer=MyModelSerializer,
)
```

The longer term fix is a bit more complicated.  The issue narrows down to the fact that wq.db's `ModelSerializer` uses the [HTML JSON Forms](https://github.com/wq/html-json-forms) parser to handle potentially nested records.  This processing happens early, so that by the time the validators run, the data is treated as if it had been submitted via a JSON API.  Since JSON differentiates between `null` and `""`, but HTML does not, I had to make an arbitrary decision how to handle empty strings when converting from an HTML Form submission to JSON (see [this function](https://github.com/wq/html-json-forms/blob/v1.0.0/html_json_forms/utils.py#L284-L300)).  I chose to treat all empty strings as null, since that was the more common interpretation in my usage.  The downside is that `blank=True` doesn't work at all.

Django REST Framework itself does not suffer from this constraint, because it has access to both the field properties and the structure of the input data at the same time (see [this function](https://github.com/tomchristie/django-rest-framework/blob/3.5.3/rest_framework/fields.py#L413-L435
)).  When `is_html_input()` is run on a dictionary that has already been processed by HTML JSON forms, it returns `False`, so the `allow_blank` handling code doesn't run.

If you aren't using nested serializers you technically don't need HTML JSON Forms at all, though I don't currently have an easy way to disable the functionality.

**Comment by tomaszn** [comment]
Another workaround: I noticed that if I set value of these non-nullable text fields to " " (a space), they are stored in the database as empty strings (without conversion to NULL).
